### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WrongProgram1** [cswil/title_view_changer#1]
![Screenshot_2020_0413_062240](https://user-images.githubusercontent.com/49438078/79081362-48790300-7d4f-11ea-90da-70b37dc2ba2a.png)

**Comment by cswil** [comment]
Its python3, and i have now added a requirements.txt file

**Comment by WrongProgram1** [comment]
Ok ill try

**Comment by WrongProgram1** [comment]
![Screenshot_2020_0413_091242](https://user-images.githubusercontent.com/49438078/79084560-ff34ad80-7d66-11ea-9741-503df57f219d.png)

Does it nornally stock here?

**Comment by cswil** [comment]
nope, mine ran instantly

**Comment by WrongProgram1** [comment]
I have an average internet connection but its stock🤔

**Comment by cswil** [comment]
![Screenshot from 2020-04-09 13-30-24](https://user-images.githubusercontent.com/56652842/79085145-4737de00-7d2f-11ea-9dab-83b9d541f3ed.png)
works fine for me still, seems to be an error on your side

**Comment by cswil** [comment]
![Screenshot from 2020-04-13 02-33-31](https://user-images.githubusercontent.com/56652842/79085174-633b7f80-7d2f-11ea-9e75-086b2fde137a.png)
works fine for me in about 2 seconds. seems to be an error on your side

**Comment by WrongProgram1** [comment]
![Screenshot_2020_0413_095700](https://user-images.githubusercontent.com/49438078/79086010-2e4e1d80-7d6d-11ea-8e3d-059e84de0a53.png)
I already installed the requirements

**Comment by cswil** [comment]
please just read the error and the readme. I am closing the issue now as this is not an issue with my code.
